"""initial revision

Revision ID: 5de6939b352b
Revises: 
Create Date: 2018-10-26 16:05:24.573799

"""
from alembic import op
import sqlalchemy as sa
from api.dictalchemy import DictAlchemy

# revision identifiers, used by Alembic.
revision = '5de6939b352b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
            'custom_element',
            sa.Column('id',sa.Integer, primary_key=True, autoincrement=True),
            sa.Column('el_id',sa.String, unique=True),
            sa.Column('el_complete',sa.Boolean, default=False),
            sa.Column('attributes',DictAlchemy()),
            sa.Column('text',sa.String),
            sa.Column('parent_id',sa.String),
            sa.Column('file_path',sa.String),
            sa.Column('file_type',sa.String),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_element')

    # ### end Alembic commands ###
